services:
  build-fe:
    build: ./fe
    volumes:
      - jsx-out:/jsx/out
    command: "npm run build"
    develop:
      watch:
        - action: sync
          path: ./fe
          target: /jsx/src

  be:
    build: ./be
    command: "hatch run uvicorn be.main:app --host 0.0.0.0 --port 8000 --reload --log-config /be/log_config.json"
    environment:
      - FORCE_COLOR=1
    ports:
      - "8000:8000"
    stop_signal: SIGINT
    develop:
      watch:
        - action: sync
          path: ./be
          target: /be/

  nginx:
    build: ./nginx
    depends_on:
      - be
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - jsx-out:/jsx-out
      - ./ssl:/ssl:ro

volumes:
  jsx-out:
